[package]
name = "boop-box"
version = "0.1.0"
authors = ["Ben Scholzen (DASPRiD) <mail@dasprids.de>"]
edition = "2021"

[dependencies]
env_logger = "0.9.0"
anyhow = "1.0.57"
log = "0.4.16"
dirs = "4.0.0"
tokio = { version = "1.17.0", features = ["full"] }
tokio-graceful-shutdown = "0.7.0"
async-trait = "0.1.53"
rppal = "0.13.1"
untildify = "0.1.0"
toml = "0.5.9"
serde = { version = "1.0.136", features = ["derive"] }
include_dir = "0.7.2"
rand = "0.8.5"
soloud = "1.0.2"
nfc1 = "0.4.0"
serde_json = "1.0.85"
wpactrl = "0.5.1"
