name: Release
on:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    if: github.actor != 'sbosnick-bot'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: semantic
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/changelog@6.0
            @semantic-release/exec@6.0
            @semantic-release/git@10.0
